application: showquestion
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /ask/.*
  script: ShowQuestion.application

- url: /.*
  script: ShowQuestion.application

libraries:
- name: numpy
  version: "1.6.1"
- name: webapp2
  version: latest


